  USE CRMCloudSchema ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('北部','','1:國內') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('中部','','1:國內') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('南部','','1:國內') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('東部','','1:國內')  ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('新加坡','東南亞銷售據點','2:國外') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('泰國','東南亞銷售據點','2:國外') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('美國','美洲銷售據點','2:國外') ;
  INSERT INTO LocationForCity 
         (LocationCityName, LocationCityDesc, LocationNation) 
         VALUES ('加拿大','美洲銷售據點','2:國外') ;